"""
Discount Recommendation Module.
Implements a transparent, rule-based business logic system for suggesting
bundle discounts based on Association Rule Mining strength (Confidence and Lift).

IMPORTANT DISCLAIMER:
- The Apriori algorithm discovers historical co-purchasing patterns (Support, Confidence, Lift).
- Apriori does NOT calculate profit margins, cost of goods sold (COGS), or price elasticity.
- The discount percentages produced by this module are heuristic business rules designed
  to test bundling strategies, NOT mathematically optimal profit-maximizing discounts.
"""

from typing import Dict, Any, Optional

DEFAULT_DISCOUNT_RULES = [
    {
        "tier": "Very Strong Relationship",
        "min_confidence": 0.70,
        "min_lift": 2.0,
        "discount_pct": 5.0,
        "rationale": (
            "Extremely high organic co-purchase affinity. Customers already buy these "
            "items together reliably; therefore, a modest 5% discount is sufficient to "
            "formalize the bundle without needlessly sacrificing margin."
        )
    },
    {
        "tier": "Strong Relationship",
        "min_confidence": 0.50,
        "min_lift": 1.5,
        "discount_pct": 10.0,
        "rationale": (
            "Solid co-purchase affinity. A 10% promotional bundle discount incentivizes "
            "customers who might otherwise purchase only the primary item."
        )
    },
    {
        "tier": "Moderate Relationship",
        "min_confidence": 0.30,
        "min_lift": 1.2,
        "discount_pct": 15.0,
        "rationale": (
            "Moderate co-purchase tendency. A higher 15% bundle discount actively stimulates "
            "cross-selling and raises average basket size."
        )
    }
]

DISCLAIMER_TEXT = (
    "Note: Discount rates are generated by heuristic business rules based on Confidence and Lift. "
    "The dataset does not contain profit margin or supplier cost data; hence, this rate is an "
    "empirical promotional recommendation, not a mathematical profit optimum."
)


def calculate_bundle_discount(
    confidence: float,
    lift: float,
    custom_rules: Optional[list] = None
) -> Dict[str, Any]:
    """
    Determine the suggested bundle discount based on association metrics.

    Parameters
    ----------
    confidence : float
        Confidence of the rule (0.0 to 1.0).
    lift : float
        Lift of the rule (> 1.0 indicates positive association).
    custom_rules : list, optional
        Custom list of discount tier dictionaries sorted from highest requirements to lowest.

    Returns
    -------
    dict
        Dictionary containing:
        - discount_pct (float): Suggested discount percentage.
        - tier (str): Name of the matched tier.
        - rationale (str): Business explanation for this discount level.
        - disclaimer (str): Theoretical disclaimer.
    """
    rules = custom_rules if custom_rules is not None else DEFAULT_DISCOUNT_RULES

    for rule in rules:
        if confidence >= rule["min_confidence"] and lift >= rule["min_lift"]:
            return {
                "discount_pct": float(rule["discount_pct"]),
                "tier": rule["tier"],
                "rationale": rule["rationale"],
                "disclaimer": DISCLAIMER_TEXT
            }

    return {
        "discount_pct": 0.0,
        "tier": "Weak Relationship / No Discount",
        "rationale": (
            "The association strength between these products does not meet the minimum "
            "thresholds (Confidence >= 0.30, Lift >= 1.20) to justify a promotional bundle discount."
        ),
        "disclaimer": DISCLAIMER_TEXT
    }
